# BaseLine Logit, self training only model seed 2023, How well does self-training model label using unseen text file? unlabel_percentage = 0.3

In [ ]:
from datasets import load_dataset
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.semi_supervised import SelfTrainingClassifier
import pandas as pd
import joblib

# https://www.codecademy.com/resources/docs/sklearn/self-training
# https://www.altexsoft.com/blog/semi-supervised-learning/
# https://scikit-learn.org/stable/modules/semi_supervised.html
# This self-training implementation is based on Yarowsky’s [1] algorithm.
# https://towardsdatascience.com/self-training-classifier-how-to-make-any-algorithm-behave-like-a-semi-supervised-one-2958e7b54ab7/

review_data = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/unlabeled_reviews.csv")


print(review_data["review_comment"].isna().sum())
review_data["review_comment"] = review_data["review_comment"].fillna("") 
review_data["recommend"] = review_data["recommend"].map({"Recommended": 1, "Not Recommended": 0})

vectorizer = TfidfVectorizer()

review_X = vectorizer.fit_transform(review_data["review_comment"])  # Convert text to TF-IDF features

# Array representing the labels. Unlabeled samples should have the label -1.
review_y = review_data["recommend"].fillna(-1)


# print(vectorizer.get_feature_names_out())  # Shows vocabulary
review_X_train, review_X_test, review_y_train, review_y_test = train_test_split(review_X, review_y, test_size=0.2, random_state=2023)

print(f"count for missing data {len(review_y_train[review_y_train==-1])}")
print(f"count for labeled data {len(review_y_train[review_y_train!=-1])}")
print(f"count for missing data_test {len(review_y_test [review_y_test ==-1])}")
print(f"count for labeled data_Test {len(review_y_test [review_y_test !=-1])}")


logit_review_model = LogisticRegression()





self_training_logit_model = SelfTrainingClassifier(logit_review_model,verbose=True)

self_training_logit_model.fit(review_X_train, review_y_train)


print(sum(review_y_pred==-1))
print(sum(review_y_test==-1))

# create a mask
mask = review_y_test != -1 
review_X_test =   review_X_test[mask]
review_y_test =  review_y_test[mask]


review_y_pred = self_training_logit_model.predict(review_X_test)


# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test , review_y_pred)
precision = precision_score(review_y_test , review_y_pred ,average='macro')
recall = recall_score(review_y_test, review_y_pred ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")
print(f"Accuracy: {accuracy:.4f}")


joblib.dump(self_training_logit_model, "base_logistic_model.pkl")
print("\nModel saved successfully.")

1
count for missing data 20073
count for labeled data 46744
count for missing data_test 4983
count for labeled data_Test 11722
End of iteration 1, added 14534 new labels.
End of iteration 2, added 803 new labels.
End of iteration 3, added 143 new labels.
End of iteration 4, added 77 new labels.
End of iteration 5, added 10 new labels.
End of iteration 6, added 13 new labels.
End of iteration 7, added 1 new labels.
End of iteration 8, added 7 new labels.
End of iteration 9, added 23 new labels.
End of iteration 10, added 16 new labels.
0
4983

Evaluation Results on Test Data:
Accuracy:  0.8544616959563215
Precision: 0.8474009780276295
Recall:    0.8120987990824307
Accuracy: 0.8545

Model saved successfully.


This tells us how the model is able to predict labels it has not seen before but does not tell us how accurate the model actually impute the data set necessarly


The data for random seed 2025 seem to very specifically yeild 0 as an accuracy result seems like I randomly pick the worse training data for it. Since logistic is fast to train I decided to make some random seed and average it

# BaseLine Logit, self training only model seed 2023, How well does self-training model impute the entire file. Not implmented yet

Metrics entire dataset,  All prediction/total lableled data

In [ ]:
from datasets import load_dataset
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.semi_supervised import SelfTrainingClassifier
import pandas as pd
import joblib

# https://www.codecademy.com/resources/docs/sklearn/self-training
# https://www.altexsoft.com/blog/semi-supervised-learning/
# https://scikit-learn.org/stable/modules/semi_supervised.html
# This self-training implementation is based on Yarowsky’s [1] algorithm.
# https://towardsdatascience.com/self-training-classifier-how-to-make-any-algorithm-behave-like-a-semi-supervised-one-2958e7b54ab7/

review_data = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/unlabeled_reviews.csv")


print(review_data["review_comment"].isna().sum())
review_data["review_comment"] = review_data["review_comment"].fillna("") 
review_data["recommend"] = review_data["recommend"].map({"Recommended": 1, "Not Recommended": 0})

vectorizer = TfidfVectorizer()

review_X = vectorizer.fit_transform(review_data["review_comment"])  # Convert text to TF-IDF features

# Array representing the labels. Unlabeled samples should have the label -1.
review_y = review_data["recommend"].fillna(-1)


# print(vectorizer.get_feature_names_out())  # Shows vocabulary
# review_X_train, review_X_test, review_y_train, review_y_test = train_test_split(review_X, review_y, test_size=0.2, random_state=2023)

# print(f"count for missing data {len(review_y_train[review_y_train==-1])}")
# print(f"count for labeled data {len(review_y_train[review_y_train!=-1])}")
# print(f"count for missing data_test {len(review_y_test [review_y_test ==-1])}")
# print(f"count for labeled data_Test {len(review_y_test [review_y_test !=-1])}")


logit_review_model = LogisticRegression()



def train_sk_single_model(dataset,model)
# dataset should be a tuple here 
    X, y = dataset
    model.fit(train_x, train_y,)
    return model


def train_



self_training_logit_model = SelfTrainingClassifier(logit_review_model,verbose=True)

# fit using the entire data set
self_training_logit_model.fit(review_X , review_y)



#-------making the test data file from full data


review_data_test = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/cleaned_reviews.csv")


print(review_data_test ["review_comment"].isna().sum())
review_data_test ["review_comment"] = review_data_test ["review_comment"].fillna("") 
review_data_test ["recommend"] = review_data_test ["recommend"].map({"Recommended": 1, "Not Recommended": 0})



review_X_test= vectorizer.transform(review_data_test ["review_comment"])  # Convert text to TF-IDF features
review_y_test = review_data_test["recommend"]


# review_X_test is the same as review_X so we are just retriveving the predicted label

review_y_pred = self_training_logit_model.predict(review_X_test)


# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test, review_y_pred)
precision = precision_score(review_y_test, review_y_pred ,average='macro')
recall = recall_score(review_y_test, review_y_pred ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")
print(f"Accuracy: {accuracy:.4f}")

1
End of iteration 1, added 18336 new labels.
End of iteration 2, added 981 new labels.
End of iteration 3, added 209 new labels.
End of iteration 4, added 49 new labels.
End of iteration 5, added 20 new labels.
End of iteration 6, added 22 new labels.
End of iteration 7, added 8 new labels.
End of iteration 8, added 53 new labels.
End of iteration 9, added 28 new labels.
End of iteration 10, added 5 new labels.
1

Evaluation Results on Test Data:
Accuracy:  0.8732310050046694
Precision: 0.8695981871592748
Recall:    0.8361131558801127
Accuracy: 0.8732


# Evaluatiing on only unlabeled data

Unlabeled prediction/unlableled data

Using the unlabeled data X as input to predict how many are labeled correctly

In [8]:

review_data_test = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/cleaned_reviews.csv")


print(review_data_test ["review_comment"].isna().sum())
review_data_test ["review_comment"] = review_data_test ["review_comment"].fillna("") 
review_data_test ["recommend"] = review_data_test ["recommend"].map({"Recommended": 1, "Not Recommended": 0})


review_X_test= vectorizer.transform(review_data_test ["review_comment"])  # Convert text to TF-IDF features
review_y_test = review_data_test["recommend"]


# only the unlabled data
mask = review_y == -1 
review_X_test =   review_X_test[mask]
review_y_test =  review_y_test[mask]


review_y_pred = self_training_logit_model.predict(review_X_test)


# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test, review_y_pred)
precision = precision_score(review_y_test, review_y_pred ,average='macro')
recall = recall_score(review_y_test, review_y_pred ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")
print(f"Accuracy: {accuracy:.4f}")

1

Evaluation Results on Test Data:
Accuracy:  0.8614303959131545
Precision: 0.8557344357789043
Recall:    0.8229421484510033
Accuracy: 0.8614


  # Implementation with random f to new data

In [33]:
from datasets import load_dataset
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.semi_supervised import SelfTrainingClassifier
import pandas as pd
import joblib

# https://www.codecademy.com/resources/docs/sklearn/self-training

# https://scikit-learn.org/stable/modules/semi_supervised.html
# This self-training implementation is based on Yarowsky’s [1] algorithm.
# https://towardsdatascience.com/self-training-classifier-how-to-make-any-algorithm-behave-like-a-semi-supervised-one-2958e7b54ab7/

review_data = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/unlabeled_reviews.csv")


print(review_data["review_comment"].isna().sum())
review_data["review_comment"] = review_data["review_comment"].fillna("") 
review_data["recommend"] = review_data["recommend"].map({"Recommended": 1, "Not Recommended": 0})

vectorizer = TfidfVectorizer()

review_X = vectorizer.fit_transform(review_data["review_comment"])  # Convert text to TF-IDF features

# Array representing the labels. Unlabeled samples should have the label -1.
review_y = review_data["recommend"].fillna(-1)


# print(vectorizer.get_feature_names_out())  # Shows vocabulary
review_X_train, review_X_test, review_y_train, review_y_test = train_test_split(review_X, review_y, test_size=0.2, random_state=2023)


random_forest_model = RandomForestClassifier(n_estimators=30, random_state=2023)



self_training_logit_model = SelfTrainingClassifier(random_forest_model,verbose=True)

self_training_logit_model.fit(review_X_train, review_y_train)

mask = review_y_test != -1 
review_X_test =   review_X_test[mask]
review_y_test =  review_y_test[mask]

review_y_pred = self_training_logit_model.predict(review_X_test)

# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test, review_y_pred )
precision = precision_score(review_y_test, review_y_pred ,average='macro')
recall = recall_score(review_y_test, review_y_pred ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")
print(f"Accuracy: {accuracy:.4f}")


joblib.dump(self_training_logit_model, "selftrain_noboot_rf_model.pkl")
print("\nModel saved successfully.")


with open('evaluation_results_selftrain_noboot_rf_model.txt', 'w') as f:
    f.write(f"Accuracy after fine-tuning: {accuracy:.4f}\n")
    f.write(f"Precision: {precision:.4f}\n")
    f.write(f"Recall: {recall:.4f}\n")


1
End of iteration 1, added 11663 new labels.
End of iteration 2, added 1743 new labels.
End of iteration 3, added 931 new labels.
End of iteration 4, added 601 new labels.
End of iteration 5, added 451 new labels.
End of iteration 6, added 283 new labels.
End of iteration 7, added 256 new labels.
End of iteration 8, added 208 new labels.
End of iteration 9, added 169 new labels.
End of iteration 10, added 162 new labels.

Evaluation Results on Test Data:
Accuracy:  0.8244326906671217
Precision: 0.8159755537925456
Recall:    0.7696756895909413
Accuracy: 0.8244

Model saved successfully.


# Random forest evluation 

Metrics entire dataset,  All prediction/total lableled data

In [ ]:
from datasets import load_dataset
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.semi_supervised import SelfTrainingClassifier
import pandas as pd
import joblib

# https://www.codecademy.com/resources/docs/sklearn/self-training
# https://www.altexsoft.com/blog/semi-supervised-learning/
# https://scikit-learn.org/stable/modules/semi_supervised.html
# This self-training implementation is based on Yarowsky’s [1] algorithm.
# https://towardsdatascience.com/self-training-classifier-how-to-make-any-algorithm-behave-like-a-semi-supervised-one-2958e7b54ab7/

review_data = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/unlabeled_reviews.csv")


print(review_data["review_comment"].isna().sum())
review_data["review_comment"] = review_data["review_comment"].fillna("") 
review_data["recommend"] = review_data["recommend"].map({"Recommended": 1, "Not Recommended": 0})

vectorizer = TfidfVectorizer()

review_X = vectorizer.fit_transform(review_data["review_comment"])  # Convert text to TF-IDF features

# Array representing the labels. Unlabeled samples should have the label -1.
review_y = review_data["recommend"].fillna(-1)


# print(vectorizer.get_feature_names_out())  # Shows vocabulary
# review_X_train, review_X_test, review_y_train, review_y_test = train_test_split(review_X, review_y, test_size=0.2, random_state=2023)

# print(f"count for missing data {len(review_y_train[review_y_train==-1])}")
# print(f"count for labeled data {len(review_y_train[review_y_train!=-1])}")
# print(f"count for missing data_test {len(review_y_test [review_y_test ==-1])}")
# print(f"count for labeled data_Test {len(review_y_test [review_y_test !=-1])}")


random_forest_model = RandomForestClassifier(n_estimators=30, random_state=2023)





self_training_logit_model = SelfTrainingClassifier(random_forest_model ,verbose=True)

self_training_logit_model.fit(review_X , review_y)



#-------making the test data file from full data


review_data_test = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/cleaned_reviews.csv")


print(review_data_test ["review_comment"].isna().sum())
review_data_test ["review_comment"] = review_data_test ["review_comment"].fillna("") 
review_data_test ["recommend"] = review_data_test ["recommend"].map({"Recommended": 1, "Not Recommended": 0})

vectorizer = TfidfVectorizer()

review_X_test= vectorizer.fit_transform(review_data_test ["review_comment"])  # Convert text to TF-IDF features
review_y_test = review_data_test["recommend"]




review_y_pred = self_training_logit_model.predict(review_X_test)


# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test, review_y_pred)
precision = precision_score(review_y_test, review_y_pred ,average='macro')
recall = recall_score(review_y_test, review_y_pred ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")
print(f"Accuracy: {accuracy:.4f}")

1
count for missing data 20073
count for labeled data 46744
count for missing data_test 0
count for labeled data_Test 83522
End of iteration 1, added 14767 new labels.
End of iteration 2, added 2144 new labels.
End of iteration 3, added 1023 new labels.
End of iteration 4, added 704 new labels.
End of iteration 5, added 507 new labels.
End of iteration 6, added 359 new labels.
End of iteration 7, added 331 new labels.
End of iteration 8, added 276 new labels.
End of iteration 9, added 246 new labels.
End of iteration 10, added 202 new labels.
1

Evaluation Results on Test Data:
Accuracy:  0.9427456239074735
Precision: 0.9435867727562016
Recall:    0.9252796810941468
Accuracy: 0.9427


In [52]:

with open('evaluation_results_selftrain_noboot__fulldta_rf_model.txt', 'w') as f:
    f.write(f"Accuracy after fine-tuning: {accuracy:.4f}\n")
    f.write(f"Precision: {precision:.4f}\n")
    f.write(f"Recall: {recall:.4f}\n")


# only unlabeld

Unlabeled prediction/unlableled data

In [ ]:

review_data_test = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/cleaned_reviews.csv")



print(review_data_test ["review_comment"].isna().sum())
review_data_test ["review_comment"] = review_data_test ["review_comment"].fillna("") 
review_data_test ["recommend"] = review_data_test ["recommend"].map({"Recommended": 1, "Not Recommended": 0})


review_X_test= vectorizer.fit_transform(review_data_test ["review_comment"])  # Convert text to TF-IDF features
review_y_test = review_data_test["recommend"]


# only the unlabled data
mask = review_y == -1 
review_X_test =   review_X_test[mask]
review_y_test =  review_y_test[mask]

review_y_pred = self_training_logit_model.predict(review_X_test)


# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test, review_y_pred)
precision = precision_score(review_y_test, review_y_pred ,average='macro')
recall = recall_score(review_y_test, review_y_pred ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")
print(f"Accuracy: {accuracy:.4f}")

1

Evaluation Results on Test Data:
Accuracy:  0.838521711366539
Precision: 0.8337905730866886
Recall:    0.7895399069999248
Accuracy: 0.8385


In [2]:

def stat_bootstrap_df(data, num_samples=1000):
    """
    Perform bootstrapping with replacement using pandas to estimate the sampling distribution of a statistic.
    
    Parameters:
    - data: A pandas Series or DataFrame.
    - num_samples: The number of bootstrap samples to generate.

    Returns:
    - bootstrap_samples: A pandas Series containing bootstrap sample statistics.
    """
    # Ensure data is a pandas Series
    if isinstance(data, pd.DataFrame):
        data = data.squeeze()  # Converts DataFrame to Series if needed
    
    bootstrap_samples = []

    for _ in range(num_samples):
        # Generate a bootstrap sample by randomly sampling with replacement
        sample = data.sample(n=len(data), replace=True)
        # Calculate the statistic (e.g., mean)
        bootstrap_samples.append(sample)

    return pd.Series(bootstrap_samples)

# bert self trianing 

In [5]:
import torch

if torch.backends.mps.is_available():
    print("MPS is available.")
else:
    print("MPS is NOT available.")

# Optional: Also check if it's built (important for some setups)
if torch.backends.mps.is_built():
    print("MPS backend is built into PyTorch.")
else:
    print("MPS backend is NOT built into PyTorch.")

MPS is available.
MPS backend is built into PyTorch.


In [ ]:
def get_predictions(model, data, batch_size=64):
    """ Get predictions on data for a classification model m returning predictions and true labels"""
    model.to("cpu")
    model.eval()
 
    all_predictions = []
    all_confidences = []
    
    if len(data['input_ids']) % batch_size != 0:
        num_batches = len(data['input_ids']) // batch_size + 1
    else:
        num_batches = len(data['input_ids']) // batch_size

    for i in tqdm(range(num_batches),desc= "Prediction Progress"):
        start_idx = i * batch_size
        end_idx = min((i + 1) * batch_size, len(data['input_ids'])) # prevent going out of bount input_ids has same size as attention mask should
        input_ids_batch = torch.tensor(data['input_ids'][start_idx:end_idx])
        attention_mask_batch = torch.tensor(data['attention_mask'][start_idx:end_idx])
        with torch.no_grad():  # Disable gradient computation for inference
            predictions = model(input_ids_batch, attention_mask=attention_mask_batch)
            logits = predictions.logits
            predictions = torch.argmax(logits, dim=-1) # make sure it is a ser
            probs = torch.nn.functional.softmax(logits, dim=-1) # return a proabiblity distribution
            max_probs, _ = torch.max(probs, dim=-1)
            
        all_confidences.append(max_probs)  # this tells us how confident we are with an value
        all_predictions.append(predictions)
        # print(predictions)
        # print("--------")
    # print(all_predictions)
    
    
    #Concatenate all batch predictions into one tensor since we currently have a list of lists
    all_predictions = torch.cat(all_predictions, dim=0)
    all_confidences = torch.cat(all_confidences, dim=0)
    
    return all_predictions , all_confidences


def self_training_loop(model, train_dataset, tokenizer, confidence_threshold=0.9, num_epochs=1, mode='unlabeled',threshold_mode = 'fix'):
    
    # still need to better develop still bad code since exit really randomly depend on the confidence_threshold which is not good for big data waiting for the final data point to set in
    
    
    data_collator = DataCollatorWithPadding(tokenizer) 
    training_args = TrainingArguments(
        num_train_epochs=num_epochs,      # Number of training epochs
    )

    
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,    # Training dataset   
        data_collator=data_collator,
    )
    
    #https://github.com/tqdm/tqdm#usage
    unlabeled_mask =  train_dataset["label"] == -1
    total_unlabeled = sum(label == -1 for label in train_dataset["label"])
    pbar = tqdm(total=total_unlabeled, desc="Unlabeled Samples Remaining")

    labeled_train_dataset = train_dataset.filter(lambda x: x["label"] != -1)
    trainer.train_dataset = labeled_train_dataset  # Update trainer with labeled dataset
    print(f"data: { labeled_train_dataset =}")
    # https://peps.python.org/pep-0289/
    print(sum(label == -1 for label in labeled_train_dataset["label"]))
    print("hello")
    trainer.train()

    while -1 in train_dataset["label"]:
        # trainer.train()
        predictions, confidences = get_predictions(model, train_dataset)
        
        if threshold_mode == 'fix':
            threshold_value = confidence_threshold
        elif threshold_mode == 'quantile':
            # this mode with too higih quantile does have converge issue
            threshold_value = torch.quantile(confidences, confidence_threshold).item()
        else:
            print("threshold mode not specified")

        print(confidences)
        print(predictions)
        print(len(train_dataset))
        print("------------------------")
        if mode == 'unlabeled':
        # we might want to make distinction here is the train_dataset label only or etc
        #  It allows you to apply a processing function to each example in a dataset, independently or in batches. This function can even create new rows and columns.
        # https://huggingface.co/docs/datasets/en/process
            condition_met_indices = [] # this is just here to keep track of the pesudo labeled added per iteration if needed
            # example here is each row
            def update_labels(example, idx):
                # Update labels for unlabeled data only, if confidence is above the threshold
                if example['label'] == -1 and confidences[idx] >= threshold_value:
                    example['label'] = predictions[idx]
                    condition_met_indices.append(idx)
                return example

            # Use .map() to apply the updates to all examples where the condition is met
            train_dataset = train_dataset.map(update_labels, with_indices=True)
            print(f"Indices where the condition was met: {condition_met_indices}")
                  

        # untested yet !!!!!!!
        elif mode == "all":
            def update_labels_all(example, idx):
                if confidences[idx] >= threshold_value:
                    example['label'] = predictions[idx]
                    condition_met_indices.append(idx)
                return example

            train_dataset = train_dataset.map(update_labels_all, with_indices=True)
            print(f"Indices where the condition was met: {condition_met_indices}")
                    
        # Update trainer with the latest training data
        pbar.update(len(condition_met_indices))
        trainer.train_dataset = train_dataset
        trainer.train()
            
        if -1 not in train_dataset["label"]:
          print("All labels are filled. Stopping training.")
          break
        
    return model, train_dataset

# testing for 5000 sample

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from sklearn.feature_extraction.text import TfidfVectorizer
from transformers import DataCollatorWithPadding
import torch
from datasets import Dataset
from trl import IterativeSFTTrainer
from tqdm import tqdm


# We are still in datafre

review_data = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/unlabeled_reviews.csv",nrows=5000)

print(review_data["review_comment"].isna().sum())
review_data["review_comment"] = review_data["review_comment"].fillna("") 
review_data["recommend"] = review_data["recommend"].map({"Recommended": 1, "Not Recommended": 0})



# vectorizer = TfidfVectorizer()

# review_X = vectorizer.fit_transform(review_data["review_comment"])  # Convert text to TF-IDF features

# # Array representing the labels. Unlabeled samples should have the label -1.

review_data["recommend"] = review_data["recommend"].fillna(-1)


print("wow")
print(review_data[review_data["recommend"]==-1])


# for some reason the tyepe matter https://discuss.huggingface.co/t/valueerror-target-size-torch-size-8-must-be-the-same-as-input-size-torch-size-8-8/12133/9
train_df = pd.DataFrame({"text": review_data["review_comment"], "label": review_data["recommend"].astype(int)})



# Now we are working with huggingface daset 

train_dataset = Dataset.from_pandas(train_df)

print(sum(label == -1 for label in train_dataset["label"]))
print(train_dataset["label"])
unlabeled_mask =  train_dataset["label"] == -1
print(unlabeled_mask)
# Load tokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

# Bert model accepts max 512
# Tokenize datasets
def tokenize(batch):
    return tokenizer(batch["text"], truncation=True, padding='max_length', max_length=512)

#------------------------------------


#------------------------------------

# In Hugging Face models like BERT, the features come from the tokenized input data that is fed into the model.
# the map applie the tokenize function to each batch of the function 
train_dataset = train_dataset.map(tokenize, batched=True)

# print(train_dataset)
# Load model
# define model
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)


model, train_dataset = self_training_loop(model, train_dataset,tokenizer)

# Save the trained model and tokenizer
model.save_pretrained("self_trained_bert_model")
tokenizer.save_pretrained("self_trained_tokenizer")

# Save the final labeled dataset
train_dataset_df = train_dataset.to_pandas()  # Convert dataset back to pandas DataFrame
train_dataset_df = train_dataset_df[["label","text"]]
train_dataset_df.to_csv("final_labeled_reviews.csv", index=False)


#---------Evaluate-----------



train_dataset_df = train_dataset.to_pandas()  # Convert dataset back to pandas DataFrame
train_dataset_df = train_dataset_df[["label","text"]]
train_dataset_df.to_csv("final_labeled_reviews.csv", index=False)
review_data_test = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/cleaned_reviews.csv",nrows=5000)



print(review_data_test ["review_comment"].isna().sum())
review_data_test ["review_comment"] = review_data_test ["review_comment"].fillna("") 
review_data_test ["recommend"] = review_data_test ["recommend"].map({"Recommended": 1, "Not Recommended": 0})
review_data_test ["recommend"] = review_data_test ["recommend"].fillna(-1)



review_y_test = review_data_test["recommend"]

train_dataset_frame =  train_dataset.to_pandas()
# only the unlabled data
mask = review_data["recommend"] == -1 
review_y_test =  review_y_test[mask]

final_data_set = train_dataset_frame[mask]
print(review_y_test)
print(final_data_set)

# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test, final_data_set["label"] )
precision = precision_score(review_y_test, final_data_set["label"]  ,average='macro')
recall = recall_score(review_y_test,final_data_set["label"]  ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")

with open('evaluation_results_selftrain_noboot_bert_models.txt', 'w') as f:
    f.write(f"Accuracy after fine-tuning: {accuracy:.4f}\n")
    f.write(f"Precision: {precision:.4f}\n")
    f.write(f"Recall: {recall:.4f}\n")



Evlautation

Unlabeled prediction/unlableled data test on full data

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from sklearn.feature_extraction.text import TfidfVectorizer
from transformers import DataCollatorWithPadding
import torch
from datasets import Dataset
from trl import IterativeSFTTrainer
from tqdm import tqdm




# We are still in datafre

review_data = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/unlabeled_reviews.csv")

print(review_data["review_comment"].isna().sum())
review_data["review_comment"] = review_data["review_comment"].fillna("") 
review_data["recommend"] = review_data["recommend"].map({"Recommended": 1, "Not Recommended": 0})



# vectorizer = TfidfVectorizer()

# review_X = vectorizer.fit_transform(review_data["review_comment"])  # Convert text to TF-IDF features

# # Array representing the labels. Unlabeled samples should have the label -1.

review_data["recommend"] = review_data["recommend"].fillna(-1)


# print("wow")
# print(review_data[review_data["recommend"]==-1])


# for some reason the tyepe matter https://discuss.huggingface.co/t/valueerror-target-size-torch-size-8-must-be-the-same-as-input-size-torch-size-8-8/12133/9
train_df = pd.DataFrame({"text": review_data["review_comment"], "label": review_data["recommend"].astype(int)})



# Now we are working with huggingface daset 

train_dataset = Dataset.from_pandas(train_df)

print(sum(label == -1 for label in train_dataset["label"]))
print(train_dataset["label"])
unlabeled_mask =  train_dataset["label"] == -1
# print(unlabeled_mask)
# Load tokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

# Bert model accepts max 512
# Tokenize datasets
def tokenize(batch):
    return tokenizer(batch["text"], truncation=True, padding='max_length', max_length=512)

#------------------------------------


#------------------------------------

# In Hugging Face models like BERT, the features come from the tokenized input data that is fed into the model.
# the map applie the tokenize function to each batch of the function 
train_dataset = train_dataset.map(tokenize, batched=True)

# print(train_dataset)
# Load model
# define model



# print (f"we are using {device}")

model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)
device = torch.device("cpu")
model.to(device)


model, train_dataset = self_training_loop(model, train_dataset, threshold_mode = 'fix')

# Save the trained model and tokenizer
model.save_pretrained("self_trained_bert_final_model")
tokenizer.save_pretrained("self_trained_final_tokenizer")

# Save the final labeled dataset
train_dataset_df = train_dataset.to_pandas()  # Convert dataset back to pandas DataFrame
train_dataset_df = train_dataset_df[["label","text"]]
train_dataset_df.to_csv("final_labeled_reviews.csv", index=False)


#---------Evaluate-----------



train_dataset_df = train_dataset.to_pandas()  # Convert dataset back to pandas DataFrame
train_dataset_df = train_dataset_df[["label","text"]]
train_dataset_df.to_csv("final_labeled_reviews.csv", index=False)
review_data_test = pd.read_csv("/Users/apple/Documents/GitHub/Steam-Market-Data-ML/cleaned_reviews.csv")



print(review_data_test ["review_comment"].isna().sum())
review_data_test ["review_comment"] = review_data_test ["review_comment"].fillna("") 
review_data_test ["recommend"] = review_data_test ["recommend"].map({"Recommended": 1, "Not Recommended": 0})
review_data_test ["recommend"] = review_data_test ["recommend"].fillna(-1)



review_y_test = review_data_test["recommend"]

train_dataset_frame =  train_dataset.to_pandas()
# only the unlabled data
mask = review_data["recommend"] == -1 
review_y_test =  review_y_test[mask]

final_data_set = train_dataset_frame[mask]
# print(review_y_test)
# print(final_data_set)

# print(review_X_train.shape[0])
# This metaestimator allows a given supervised classifier to function as a semi-supervised classifier, allowing it to learn from unlabeled data. 
# It does this by iteratively predicting pseudo-labels for the unlabeled data and adding them to the training set.

accuracy = accuracy_score(review_y_test, final_data_set["label"] )
precision = precision_score(review_y_test, final_data_set["label"]  ,average='macro')
recall = recall_score(review_y_test,final_data_set["label"]  ,average='macro')


print("\nEvaluation Results on Test Data:")
print(f"Accuracy:  {accuracy}")
print(f"Precision: {precision}")
print(f"Recall:    {recall}")

with open('evaluation_results_selftrain_noboot_full_bert_models.txt', 'w') as f:
    f.write(f"Accuracy after fine-tuning: {accuracy:.4f}\n")
    f.write(f"Precision: {precision:.4f}\n")
    f.write(f"Recall: {recall:.4f}\n")



1
25056
[-1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1, 1, 0, 1, 1, -1, 1, 0, 1, -1, 1, -1, 1, -1, 0, 1, -1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 0, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1, -1, 1, 0, 1, 1, -1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, -1, -1, 1, -1, 1, 1, 1, 1, -1, 1, -1, 0, -1, 1, -1, 0, 1, 0, -1, -1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, -1, 1, 1, 1, 1, -1, -1, 1, 1, 1, -1, 1, 1, 1, 1, -1, 0, 1, 1, 1, 1, 1, -1, 1, 1, 0, 1, 1, -1, 1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, -1, -1, -1, -1, -1, 1, -1, 1, -1, -1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1, 1, -1

Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Unlabeled Samples Remaining:   0%|          | 0/25056 [00:00<?, ?it/s]

Filter:   0%|          | 0/83522 [00:00<?, ? examples/s]

data:  labeled_train_dataset =Dataset({
    features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 58466
})
0
hello


/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Step,Training Loss
500,0.424400
1000,0.395400
1500,0.371500
2000,0.369600
2500,0.344800
3000,0.345100
3500,0.319900
4000,0.318900
4500,0.321800
5000,0.303600


Prediction Progress: 100%|██████████| 1306/1306 [13:55:47<00:00, 38.40s/it]

tensor([0.9092, 0.9805, 0.9984,  ..., 0.9939, 0.9360, 0.9959])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------


Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining:  84%|████████▍ | 21039/25056 [16:20:57<3:07:17,  2.80s/it]

Indices where the condition was met: [0, 9, 13, 17, 39, 42, 48, 52, 56, 59, 67, 68, 72, 74, 76, 78, 82, 90, 95, 96, 100, 104, 106, 107, 108, 115, 117, 119, 121, 125, 126, 127, 130, 138, 140, 143, 150, 153, 155, 158, 160, 161, 165, 166, 168, 174, 178, 183, 190, 196, 201, 204, 206, 212, 216, 217, 243, 244, 245, 246, 251, 257, 265, 270, 272, 273, 274, 276, 278, 279, 285, 286, 287, 288, 289, 292, 294, 300, 302, 307, 311, 315, 316, 317, 324, 325, 327, 329, 330, 345, 346, 350, 352, 354, 358, 362, 363, 367, 369, 378, 388, 391, 397, 398, 403, 408, 415, 417, 420, 425, 428, 433, 436, 437, 438, 439, 444, 446, 448, 449, 451, 457, 463, 467, 472, 475, 481, 482, 497, 499, 508, 521, 533, 535, 540, 543, 545, 546, 548, 549, 552, 554, 557, 558, 563, 566, 567, 568, 569, 583, 585, 588, 593, 594, 595, 600, 602, 611, 614, 615, 616, 617, 627, 628, 632, 633, 634, 640, 643, 644, 646, 648, 653, 656, 657, 661, 676, 677, 681, 687, 690, 692, 693, 695, 700, 701, 704, 705, 709, 712, 714, 718, 721, 723, 727, 732, 733,

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Step,Training Loss
500,0.228700
1000,0.225200
1500,0.273500
2000,0.258600
2500,0.252900
3000,0.250100
3500,0.246200
4000,0.233400
4500,0.247000
5000,0.233900


Prediction Progress: 100%|██████████| 1306/1306 [14:43:24<00:00, 40.59s/it]

tensor([0.9978, 0.9966, 0.9987,  ..., 0.9952, 0.9921, 0.9985])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------


Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining:  96%|█████████▌| 23981/25056 [34:52:46<1:49:25,  6.11s/it]

Indices where the condition was met: [18, 26, 54, 80, 88, 110, 208, 214, 271, 295, 310, 340, 374, 474, 520, 524, 584, 606, 607, 629, 667, 696, 703, 744, 901, 934, 970, 1120, 1156, 1162, 1171, 1227, 1235, 1288, 1303, 1305, 1347, 1361, 1443, 1466, 1645, 1729, 1758, 1898, 1901, 1922, 2077, 2110, 2137, 2174, 2352, 2385, 2402, 2508, 2618, 2647, 2699, 2791, 2824, 2828, 2831, 2844, 2970, 3004, 3022, 3116, 3195, 3233, 3270, 3278, 3300, 3354, 3358, 3403, 3407, 3443, 3513, 3523, 3576, 3667, 3683, 3696, 3734, 3767, 3910, 3916, 3938, 3975, 4021, 4058, 4110, 4240, 4245, 4253, 4260, 4341, 4454, 4559, 4562, 4601, 4618, 4662, 4685, 4767, 4850, 4865, 4873, 4889, 4894, 4906, 4915, 4927, 4929, 4934, 4953, 4967, 4981, 4984, 5018, 5030, 5041, 5049, 5057, 5078, 5090, 5091, 5110, 5115, 5136, 5148, 5150, 5153, 5162, 5184, 5187, 5239, 5364, 5368, 5420, 5423, 5463, 5553, 5622, 5627, 5657, 5706, 5888, 5899, 5912, 5949, 6067, 6111, 6190, 6229, 6234, 6318, 6481, 6525, 6530, 6561, 6562, 6596, 6611, 6637, 6663, 6664

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Step,Training Loss
500,0.185400
1000,0.205200
1500,0.212900
2000,0.213100
2500,0.240700
3000,0.212900
3500,0.220600
4000,0.205000
4500,0.211300
5000,0.214100


Prediction Progress: 100%|██████████| 1306/1306 [14:34:20<00:00, 40.17s/it]

tensor([0.9985, 0.9899, 0.9977,  ..., 0.9976, 0.9958, 0.9985])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------


Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining:  99%|█████████▊| 24735/25056 [52:49:56<57:08, 10.68s/it]  

Indices where the condition was met: [199, 912, 1046, 1429, 1569, 1835, 2368, 3606, 3804, 4029, 4292, 4296, 4299, 4309, 4320, 4351, 4400, 4453, 4543, 4563, 4638, 4792, 4939, 5032, 5067, 5093, 5134, 5190, 5220, 5713, 5761, 5788, 6078, 6538, 6581, 6615, 6632, 6670, 6816, 6846, 6847, 7903, 8083, 8084, 8230, 8772, 8900, 9217, 9624, 10387, 10450, 10791, 11054, 11120, 11279, 11313, 11624, 11673, 11869, 11966, 12235, 12236, 12382, 12400, 12455, 12535, 12605, 12639, 12670, 12791, 12836, 12976, 13289, 13378, 13534, 13765, 13939, 13969, 14047, 14234, 14371, 14671, 14747, 14750, 14801, 14842, 14864, 14880, 14928, 15090, 15148, 15304, 15345, 16684, 17107, 17268, 17339, 18219, 18375, 18640, 18993, 19042, 19089, 19103, 19174, 19992, 20425, 20443, 20843, 21539, 21980, 22120, 22373, 22575, 22580, 22592, 22641, 22685, 22953, 23034, 23127, 23189, 23288, 23366, 23459, 23693, 23767, 23785, 23790, 23900, 23964, 24272, 24399, 24837, 24910, 24936, 25154, 25305, 25756, 25775, 25934, 26231, 26278, 26522, 27057

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Step,Training Loss
500,0.149600
1000,0.158600
1500,0.192800
2000,0.191900
2500,0.195100
3000,0.200300
3500,0.178900
4000,0.192300
4500,0.197000
5000,0.206500


Prediction Progress: 100%|██████████| 1306/1306 [14:42:40<00:00, 40.55s/it]

tensor([0.9981, 0.9976, 0.9979,  ..., 0.9976, 0.9932, 0.9981])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------


Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining:  99%|█████████▉| 24897/25056 [70:58:29<46:19, 17.48s/it]

Indices where the condition was met: [3453, 4469, 5069, 5157, 5774, 6241, 6862, 7489, 11772, 12860, 14496, 15286, 16106, 16128, 16275, 18048, 18484, 18921, 19601, 19612, 21151, 22187, 22219, 23115, 23596, 23705, 24683, 25041, 25572, 26264, 29431, 30532, 32361, 32919, 34282, 35355, 35919, 36232, 36978, 37568, 37753, 37844, 37993, 38190, 38458, 38651, 38797, 39238, 39429, 39461, 39651, 39954, 41256, 41766, 42485, 42548, 43266, 43571, 44498, 44914, 45286, 46729, 46912, 47079, 47444, 47597, 48842, 49115, 49191, 49198, 49248, 49513, 49532, 49678, 50412, 50742, 51428, 51664, 51902, 52161, 52295, 52581, 52732, 52937, 52957, 53265, 53509, 55304, 56558, 58511, 58555, 58745, 59192, 59305, 59403, 59981, 60049, 60231, 60498, 61035, 61264, 64413, 65141, 65515, 65792, 65954, 66316, 66413, 66529, 66825, 67460, 67512, 67598, 67602, 67644, 67694, 68124, 68179, 68634, 68773, 69113, 69741, 69973, 70341, 70510, 70775, 70848, 71088, 71337, 71557, 72093, 72523, 72600, 73101, 73248, 73311, 73315, 74378, 7443

/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Step,Training Loss
500,0.123800
1000,0.141800
1500,0.182500
2000,0.158700
2500,0.166300
3000,0.161600
3500,0.177600
4000,0.149900
4500,0.164700
5000,0.183000


Prediction Progress: 100%|██████████| 1306/1306 [14:46:08<00:00, 40.71s/it]

tensor([0.9977, 0.9975, 0.9976,  ..., 0.9969, 0.9976, 0.9979])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------


Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining: 100%|█████████▉| 24951/25056 [89:08:49<47:41, 27.26s/it]

Indices where the condition was met: [173, 3821, 3918, 6817, 8570, 13340, 14822, 15890, 16471, 16877, 17258, 17313, 22779, 23340, 24933, 28777, 30263, 30491, 31098, 31746, 34908, 35987, 36259, 41204, 43854, 47464, 47859, 48083, 48422, 49014, 50578, 50914, 51531, 52199, 60193, 64547, 64892, 67345, 67655, 67837, 68245, 68763, 69107, 69744, 69842, 71867, 73060, 75408, 75581, 75878, 80662, 81553, 81806, 82862]


/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Step,Training Loss
500,0.119700
1000,0.116500
1500,0.155200
2000,0.136400
2500,0.160300
3000,0.156400
3500,0.131900
4000,0.138900
4500,0.159500
5000,0.171800


Prediction Progress: 100%|██████████| 1306/1306 [14:35:26<00:00, 40.22s/it]

tensor([0.9973, 0.9979, 0.9983,  ..., 0.9963, 0.9963, 0.9983])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------


Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining: 100%|█████████▉| 24973/25056 [107:31:34<57:15, 41.39s/it]

Indices where the condition was met: [4952, 5145, 5260, 14148, 19735, 21060, 27870, 34077, 37999, 42206, 43601, 45977, 48381, 50456, 50873, 51311, 64655, 65817, 66089, 66261, 71029, 76525]


/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Step,Training Loss
500,0.109800
1000,0.119800
1500,0.142100
2000,0.138000
2500,0.163300
3000,0.163800
3500,0.147100
4000,0.145800
4500,0.162100
5000,0.158800


Prediction Progress: 100%|██████████| 1306/1306 [14:39:21<00:00, 40.40s/it]

tensor([0.9977, 0.9973, 0.9980,  ..., 0.9966, 0.9980, 0.9976])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------


Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining: 100%|█████████▉| 24991/25056 [125:43:52<1:06:19, 61.22s/it]

Indices where the condition was met: [27690, 33660, 43828, 46982, 47098, 53820, 61664, 66001, 66912, 67567, 67776, 68481, 70433, 70634, 73575, 73578, 76992, 78456]


/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Step,Training Loss
500,0.090300
1000,0.119200
1500,0.146800
2000,0.167400
2500,0.132400
3000,0.142300
3500,0.127700
4000,0.151300
4500,0.142700
5000,0.153500


Prediction Progress: 100%|██████████| 1306/1306 [14:08:48<00:00, 39.00s/it]

tensor([0.9979, 0.9978, 0.9980,  ..., 0.9952, 0.9976, 0.9976])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------


Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Indices where the condition was met: []


/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Step,Training Loss
500,0.104200
1000,0.101800
1500,0.134500
2000,0.141200
2500,0.135900
3000,0.148000
3500,0.123300
4000,0.135700
4500,0.135800
5000,0.147400


Prediction Progress: 100%|██████████| 1306/1306 [14:23:07<00:00, 39.65s/it]

tensor([0.9968, 0.9982, 0.9984,  ..., 0.9938, 0.9981, 0.9976])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------


Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining: 100%|█████████▉| 24998/25056 [161:11:16<1:52:48, 116.70s/it]

Indices where the condition was met: [51552, 57162, 71092, 73910, 74020, 76996, 81852]


/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Step,Training Loss
500,0.101700
1000,0.178300
1500,0.177900
2000,0.120200
2500,0.147100
3000,0.148600
3500,0.114900
4000,0.157200
4500,0.139400
5000,0.142300


Prediction Progress: 100%|██████████| 1306/1306 [14:22:03<00:00, 39.60s/it]

tensor([0.9971, 0.9966, 0.9978,  ..., 0.9949, 0.9972, 0.9966])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------


Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining: 100%|█████████▉| 25031/25056 [179:03:02<1:03:59, 153.60s/it]

Indices where the condition was met: [1169, 6167, 9385, 21778, 26741, 27938, 28274, 45993, 47942, 48508, 48536, 49691, 50171, 50773, 54742, 55498, 56184, 58874, 59153, 61814, 65816, 67881, 69138, 69587, 69819, 69893, 70009, 70840, 71369, 73017, 73051, 75775, 76293]


/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Step,Training Loss
500,0.108400
1000,0.126600
1500,0.189500
2000,0.156200
2500,0.187700
3000,0.170600
3500,0.155900
4000,0.179800
4500,0.189600
5000,0.585500


Prediction Progress: 100%|██████████| 1306/1306 [14:20:16<00:00, 39.52s/it]

tensor([0.9951, 0.9955, 0.9958,  ..., 0.9957, 0.9960, 0.9958])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------


Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining: 100%|█████████▉| 25053/25056 [196:46:10<10:15, 205.28s/it]  

Indices where the condition was met: [5096, 16647, 23470, 67854, 68840, 69753, 72272, 72518, 73070, 73099, 73589, 74523, 75336, 75764, 76281, 76679, 76962, 77019, 77022, 77221, 77274, 77397]


/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Step,Training Loss
500,0.150600
1000,0.148200
1500,0.184900
2000,0.330800
2500,0.544500
3000,0.601600
3500,0.483000
4000,0.199300
4500,0.148000
5000,0.168400


Prediction Progress: 100%|██████████| 1306/1306 [14:26:45<00:00, 39.82s/it]

tensor([0.9966, 0.9968, 0.9969,  ..., 0.9957, 0.9968, 0.9963])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------


Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Indices where the condition was met: []


/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Step,Training Loss
500,0.137300
1000,0.145200
1500,0.172300
2000,0.177900
2500,0.198300
3000,0.178200
3500,0.172700
4000,0.151500
4500,0.146100
5000,0.137400


Prediction Progress: 100%|██████████| 1306/1306 [14:34:11<00:00, 40.16s/it]

tensor([0.9933, 0.9934, 0.9935,  ..., 0.9930, 0.9933, 0.9935])
tensor([1, 1, 1,  ..., 1, 1, 1])
83522
------------------------


Map:   0%|          | 0/83522 [00:00<?, ? examples/s]

Unlabeled Samples Remaining: 100%|██████████| 25056/25056 [232:46:15<00:00, 362.36s/it]

Indices where the condition was met: [58925, 69625, 75283]


/opt/anaconda3/envs/cosc410_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py:685: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Step,Training Loss
500,0.129100
1000,0.152000
1500,0.167700
2000,0.214200
2500,0.176700
3000,0.220200
3500,0.216500
4000,0.179500
4500,0.220100
5000,0.215300


Unlabeled Samples Remaining: 100%|██████████| 25056/25056 [236:18:38<00:00, 33.95s/it] 

All labels are filled. Stopping training.


1

Evaluation Results on Test Data:
Accuracy:  0.9040948275862069
Precision: 0.8941426768586276
Recall:    0.8868404755714969
